apiVersion: v1
kind: Service
metadata:
  name: maestro-bridge
  namespace: maestro-bridge
  labels:
    app.kubernetes.io/name: maestro-bridge
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: maestro-bridge
